// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuid
{
    internal sealed partial class Vsix
    {
        public const string Id = "InsertGuid.a7f25cf2-aa0e-4a26-bd33-792450af2a6d";
        public const string Name = "Insert Guid";
        public const string Description = @"Insert a guid into the editor.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Andrew Basil";
        public const string Tags = "";
    }
}
